### ISSUE TITLE
how to run the try_vectors

### ISSUE THREAD

**Issue by mattcorkum** [dperezrada/keywords2vec#2]
python try_keywords2vec.py -v data/experiments/episte_30000/word2vec.vec -n episte_30000 -p "obesity" 

There needs to be a space between.

I also had to adjust the movement of data.

I had copied the data to the top directory. This works great for the model building. Then I moved the resultant files into the nlp/keywords/data location in order to be able to run the above command successfully.

The data directory gets created in the nlp/keywords/data location. 

Produces this.
python try_keywords2vec.py -v data/experiments/episte_30000/word2vec.vec -n episte_30000 -p "obesity"
                       term     score  counter
0                overweight  0.693945      297
1                     obese  0.617680      152
2         obese individuals  0.614914       15
3              obese adults  0.606311       28
4        insulin resistance  0.589740       85
5              obese people  0.573590       13
6         glucose tolerance  0.570195        6
7         bariatric surgery  0.554315       83
8            obese subjects  0.552010       13
9              dyslipidemia  0.549108       28
10              weight loss  0.546550      364
11            dyslipidaemia  0.542751       18
12       metabolic syndrome  0.541280       85
13     intragastric balloon  0.536888        5
14              underweight  0.523899       14
15    body fat distribution  0.520858        3
16     childhood overweight  0.519322       10
17            dental caries  0.518739       61
18                  dietary  0.518213       61
19  cardiovascular diseases  0.517509      100
20        metabolic disease  0.516839        6
21         white caucasians  0.510198        4
22                      bmi  0.508312      247
23     childhood-onset type  0.508124        4
24     lifestyle management  0.501618        5

**Comment by dperezrada** [comment]
Thanks @mattcorkum for notice that.
Now it's only needed the path to the vectors to run it, like this:

```
python try_keywords2vec.py -v data/experiments/episte_30000/word2vec.vec -p "obesity"
```
Let me know if it works for you.

**Comment by dperezrada** [comment]
This is no longer a command line. Now is a python library, closing this issue.
